### ISSUE TITLE
This addon causes Windows to have no effect on adjusting NVDA's volume.

### ISSUE THREAD

**Issue by cary-rowen** [josephsl/soundSplitter#2]
Press Win + R to open the run dialog box, enter the following command:
`ms-settings:apps-volume`

Locate NVDA Application in the list and try to adjust its volume using the slider.

You will find that this cannot be done.
NVDA can only decrease one value, and back to the other.

**Comment by josephsl** [comment]
Hi, this is due to the fact that the add-on forcefully sets NVDA volume to 100 percent all the time, borrowed from Tony’s Enhancements add-on. If Tony did resolve this in later add-on releases, then I might be able to incorporate his fix, otherwise I’m afraid it won’t be resolved at this time (sorry). Thanks.

**Comment by cary-rowen** [comment]
Hi, @XLTechie 
Would you reconsider fixing this.

**Comment by XLTechie** [comment]
This has not been solved in Tony's original add-on either, as Joseph suggested.

This is an ugly bug, however, I will work on it along with the WASAPI fix.
